### ISSUE TITLE
Expand `examples_do_not_have_gitignore` test

### ISSUE THREAD

**Issue by smoelius** [trailofbits/dylint#1417]
To `examples_do_not_contain_forbidden_paths` or something similar:
https://github.com/trailofbits/dylint/blob/dad4f73484a0c30596afd7a1834a02cc83fc7914/examples/src/lib.rs#L101

The test should continue check that the following is not in any example subdirectory:
- .gitignore

The test should additionally check that the following are not in any non-root subdirectory of the general, supplementary, or restriction subdirectories:
- .cargo/config.toml
- rust-toolchain

However, the test should allow those files to exist in the experimental and testing subdirectories, e.g., like here:
- https://github.com/trailofbits/dylint/blob/master/examples/experimental/derive_opportunity/.cargo/config.toml
- https://github.com/trailofbits/dylint/blob/master/examples/testing/straggler/rust-toolchain

**Comment by 0x471** [comment]
Hi, can I work on this issue? @smoelius

**Comment by smoelius** [comment]
@0x471 Yes, please do!

**Comment by smoelius** [comment]
I just clarified the issue description a little bit. I think the changes are small. Hopefully, you agree.

**Comment by 0x471** [comment]
Thank you for the details, feel free to check the PR!

it seems the test is currently failing because there’s a rust-toolchain file in the general examples folder.  According to the issue description, this file shouldn’t be there. 

How do you suggest proceeding with this?

**Comment by smoelius** [comment]
> it seems the test is currently failing because there’s a rust-toolchain file in the general examples folder.

That's okay, actually.

In fact, my reason for wanting to expand the test is to ensure that no file in a subdirectory overrides those.

I'm not sure the easiest/best way to suggest allowing exceptions for the roots of the general, supplementary, and restriction subdirectories. Can I leave it to you to decide?

P.S. I just tweaked the description again. Sorry for being imprecise.

**Comment by 0x471** [comment]
I modified the test accordingly, added a new array for root directories with exceptions: https://github.com/trailofbits/dylint/pull/1461/commits/f49cf2365dcd07fbe18e6ed4d021ca72cdae1c33
