### ISSUE TITLE
Does dylint support automatic fix?

### ISSUE THREAD

**Issue by keiichiw** [trailofbits/dylint#146]
Can dylint automatically apply lint suggestions with `Applicability::MachineApplicable` like `cargo clippy --fix`?

**Comment by smoelius** [comment]
It doesn't currently, but I can certainly look into it.

**Comment by smoelius** [comment]
@keiichiw I think I have this working an you are welcome to try it out, if you like:
```sh
cargo install cargo-dylint dylint-link --git https://github.com/trailofbits/dylint --branch fix-option
```
Either way, I will likely merge and publish this within the next few days.
