### ISSUE TITLE
[Discussion] How does it work with vscode ext ?

### ISSUE THREAD

**Issue by haoadoresorange** [trailofbits/dylint#26]
I'm interested in using Dylint since I need to maintain different custom lint rules. I'm not figuring out yet how to integrate it with vscode ext tho since the extension use Clippy by default.
Do you have experience regarding this matter ?
Thanks !

**Comment by smoelius** [comment]
Unfortunately, I don't have any experience writing VS Code plugins.

Could you say a little bit about how Clippy works with VS Code?

**Comment by haoadoresorange** [comment]
From what I know it works as a similar manner like eslint...etc. The plugin look for the executable clippy on the machine, and then execute as the code is written and report back to the vscode to display whatever the error is.
I looked into it a bit but seems there is no way to specify the path for the linter for example.

**Comment by smoelius** [comment]
> I looked into it a bit but seems there is no way to specify the path for the linter for example.

So is your intent then to modify this extension to use Dylint instead of Clippy?

Could you point us to the extension?

One thing I am confused about is what "version" of the files the extension operates on. Both Clippy and Dylint take time to run. In principle, the source code could change between the time the linter is invoked and when it finishes, e.g., line numbers could change. I am wondering how this problem is dealt with now.

**Comment by haoadoresorange** [comment]
Hi, so I looked a bit more today.
There are currently 2 extensions on vscode: Rust (use rls) and Rust-Analyzer (use rust-analyzer). So the Rust extension seems having no option to change the linting command, it calls clippy by default. The Rust-Analyzer extension however has an option to change the command called on save (which is `cargo check` by default), I posted a question [here](https://github.com/rust-analyzer/rust-analyzer/issues/9340).
So I find out that `clippy` and `cargo check` shares the same JSON output protocol, hence changing the command on save result in linting error reported seemelessly.
Does Dylint always follow such protocol ?

**Comment by haoadoresorange** [comment]
> 
> 
> > I looked into it a bit but seems there is no way to specify the path for the linter for example.
> 
> One thing I am confused about is what "version" of the files the extension operates on. Both Clippy and Dylint take time to run. In principle, the source code could change between the time the linter is invoked and when it finishes, e.g., line numbers could change. I am wondering how this problem is dealt with now.

From what I see the command is invoked on save event, so each time it is interrupted and invoked again.

**Comment by lnicola** [comment]
Hey, coming from the RA side to answer here. You're right about the race between saving a file and the linter finishing. There's an example at https://github.com/rust-analyzer/rust-analyzer/issues/4266, but it doesn't come up too often in practice.

Ideally, we'd have a (documented and relatively stable) interface to share the modified files with rustc, which dylint could probably use, but that seems pretty far, to be honest.

**Comment by smoelius** [comment]
Thanks for the explanations, @haoadoresorange, @lnicola.

> Does Dylint also follow such protocol ?

Like Clippy, Dylint runs `cargo check` under-the-hood, and anything passed to Dylint after `--` is passed to `cargo check`.

I just tried this, and I think maybe it's working(???):
```
    "rust-analyzer.checkOnSave.overrideCommand": [
        "cargo",
        "dylint",
        "--all",
        "--workspace",
        "--",
        "--message-format=json"
    ]
```

**Comment by lnicola** [comment]
Yeah, that looks good.

**Comment by smoelius** [comment]
Hi, @haoadoresorange. I updated the README to include what we learned here: https://github.com/trailofbits/dylint#vs-code-integration

Do you think I can close this issue?

**Comment by heaths** [comment]
But if we [override the checkOnSave command](https://github.com/trailofbits/dylint/blob/master/README.md#vs-code-integration) to use `dylint` instead of `clippy` (considering we already overrode it to run `clippy`), we are missing on *large* number of lints just to run a few of our own. Is there some way to get `dylint` to run `clippy` or at least process its lints as well? I.e., we want to run clippy's vast trove of lints as well as our couple of custom ones.

**Comment by smoelius** [comment]
> But if we [override the checkOnSave command](https://github.com/trailofbits/dylint/blob/master/README.md#vs-code-integration) to use `dylint` instead of `clippy` (considering we already overrode it to run `clippy`), we are missing on _large_ number of lints just to run a few of our own. Is there some way to get `dylint` to run `clippy` or at least process its lints as well?

Right now, I know of only two ways to do this:
1. **Use the Clippy library that Dylint includes for testing purposes.** E.g., add something like the following to your Cargo.toml file:
   ```toml
   [workspace.metadata.dylint]
   libraries = [
       { git = "https://github.com/trailofbits/dylint", pattern = "examples/testing/clippy" },
   ]
   ```
   A downside of this approach is that we cannot guarantee the Clippy version that provides. For example, right now it is https://github.com/rust-lang/rust-clippy/commit/37f4fbb92913586b73a35772efd00eccd1cbbe13 (1.82), but it is going to soon switch to https://github.com/rust-lang/rust-clippy/commit/a95afe2d0a2051d97b723b0b197393b7811bc4e4 (1.83).
2. **Run Clippy and Dylint separately, and combine there outputs using scripting.** Some ideas for this were put forth in https://github.com/trailofbits/dylint/issues/1274#issuecomment-2263225049.
