### ISSUE TITLE
support for `--message-format json` like feature.

### ISSUE THREAD

**Issue by lgirletti** [trailofbits/dylint#398]
I was wondering if the output of the Dylint libraries is somehow standardized or if it is specific per library and if there is something similar to `--message-format json` (used in Cargo Clippy) to retrieve the output in JSON format and parse it easily.

If the answer is no, then it could be a good feature to add in Dylint.

**Comment by smoelius** [comment]
Passing `-- --message-format json` should work.

Like Clippy, Dylint is essentially a wrapper around `cargo check`. A difference, though, is that Clippy forwards its arguments directly to `cargo check`, whereas Dylint requires arguments for `cargo check` to be passed after `--`.

You can see an example use here: https://github.com/trailofbits/dylint#vs-code-integration

Please let me know if I have misunderstood.

**Comment by lgirletti** [comment]
I was missing the extra `--` . Thanks for the quick answer!
