### ISSUE TITLE
How to reliably choose the correct `clippy_utils` git revision for a corresponding nightly toolchain

### ISSUE THREAD

**Issue by mattvmsft** [trailofbits/dylint#514]
My apologies if there is a better place to ask this question, I did not see a discussions section in this repo so if there is another forum where this type of question should be asked, please let me know! 

#499 updates the lint examples to use a more recent nightly and also updates the git revision for the `clippy_utils` dependency. Is there a reliable (or potentially automatable) process for determining which `rust-clippy` commit to use for a given nightly? 

Thanks!

**Comment by smoelius** [comment]
Asking questions here is totally cool. 👍

For a library stored in `<PATH>`, `cargo dylint upgrade <PATH>` should upgrade the library's `clippy_utils` dependency and `rust-toolchain` to those from the most recent Clippy version bump.

That's actually how Dylint's CI generates PRs like the once you cited.

Beyond that, there's no good answer, AFAIA. Under the hood, `cargo upgrade` analyzes Clippy's commit history. I don't know of a better approach than this.

For me personally, though, I rarely find myself needing to know more than what `cargo upgrade` provides.

**Comment by mattvmsft** [comment]
Got it, thanks for the info!

**Comment by mattvmsft** [comment]
Follow up question from poking around the `cargo dylint upgrade` help docs: I noticed there is a `rust-version` option to upgrade to a specific tag, however it seems like the [tags ](https://github.com/rust-lang/rust-clippy/tags) for the `rust-clippy` repo were not updated for 1.65 or beyond, do you know if that procedure for tagging a commit with a rust version has been discontinued?

**Comment by smoelius** [comment]
I'm not sure, TBH. Maybe it's a manual process that sometimes gets overlooked(?).

Aside: `cargo dylint upgrade` used to use the tags, but no longer does for essentially this reason.
