### ISSUE TITLE
Update Rust toolchain version?

### ISSUE THREAD

**Issue by smoelius** [trailofbits/dylint#837]
Copied from https://github.com/rust-lang/rust-clippy/issues/11490:

> I am using the `clippy_utils` crate for developing [`dylint`](https://github.com/trailofbits/dylint) programs. I need to add the `clippy_utils` that matches the toolchain I am using (currently `1.74.0-nightly`) to my `Cargo.toml` as a lib dependency. I can’t add this dependency from the `rust` repository because the repository is too big, so I have to use a version from the `rust-clippy` repository.

_Originally posted by @EFanZh in https://github.com/rust-lang/rust-clippy/issues/11490#issuecomment-1717588599_

**Comment by smoelius** [comment]
> I need to add the clippy_utils that matches the toolchain I am using (currently 1.74.0-nightly)

Sorry, does that mean you're using the latest nightly?

We recommend pinning to a specific date, to avoid the kinds of problems you seem to be describing ([example](https://github.com/trailofbits/dylint/blob/c78bd5decebf1c98fe5d79a9b108bd2a71775804/examples/restriction/assert_eq_arg_misordering/rust-toolchain#L2)).

Is there a reason why that strategy wouldn't work for you? (Or have I misunderstood your problem?)

**Comment by EFanZh** [comment]
No, we do pin the Rust toolchain version, but the version we need have to be at least `nightly-2023-09-10`. Because there are some compiler features that our project requires, that have just been added to the compiler.

**Comment by smoelius** [comment]
OK. (Sorry for misunderstanding.)

I can see three possible courses of action.

1. Wait until the next Rust-Clippy sync. Like Alexandoo said, they happen every two weeks, and here was the last one: https://github.com/rust-lang/rust-clippy/pull/11469 So I would expect the next be sometime mid next week.

2. Fork Clippy, apply the updates yourself, and use that fork (at least until Clippy is updated).

3. To my amazement(!), you can use the Rust repo as the source for `clippy_utils`, e.g.:
```toml
clippy_utils = { git = "https://github.com/rust-lang/rust", rev = "8ed4537d7" }
```
That commit came from `rustc --version`, e.g.:
```
$ rustc --version
rustc 1.74.0-nightly (8ed4537d7 2023-09-09)
```
Note that it takes a looong time for Cargo to download Rust as a dependency. But it's a onetime cost, and it's probably quicker than applying the updates yourself as in option 2.

**Comment by EFanZh** [comment]
I think I’ll wait 7 days for the next sync. Thank you for your help!
